# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.3.0'

gem 'json', '< 3.0'
gem 'puma', '~> 8.0'
gem 'rack-cors'
gem 'rails', '~> 8.0'
gem 'redis', '~> 5.1'
group :development, :test do
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
end
