# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'activesupport', '>= 7.0'
  gem 'ostruct'
  gem 'rspec', '~> 3.0'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'simplecov'
  gem 'webmock'
end
