source 'https://rubygems.org'

ruby '>= 3.3.0'

gem 'rails', '~> 8.0'
gem 'puma', '~> 8.0'
gem 'rack-cors'
gem 'json', '< 3.0'

gem 'oauth2_client_kit', path: '../oauth2_client_kit'
group :development, :test do
  gem 'rspec-rails'
  gem 'simplecov', require: false
end
